name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'release/*'
  workflow_dispatch:

jobs:
  build_application:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: restore packages
        run: dotnet restore
      - name: build
        run: dotnet build -c Release --no-restore
      - name: Get version
        run: |
              export VER=$(grep -oP '\d+\.\d+\.\d+(?=</PackageVersion>)' src/Behavioral.Automation/Behavioral.Automation.csproj)
              echo "VER=$VER" >> $GITHUB_ENV
              echo $VER
      - name: Package app
        run: |
          dotnet pack ./src/Behavioral.Automation/Behavioral.Automation.csproj \
          --configuration Release /p:Platform=\"AnyCPU\" \
          /p:PackageVersion=${{ env.VER }} --output ./
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VER }}
          artifacts: "Behavioral.Automation.${{ env.VER }}.nupkg"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish app into nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.QUANTORI_NUGET_API_KEY }}
        run: dotnet nuget push ./Behavioral.Automation.${{ env.VER }}.nupkg -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate
