name: Selenium project tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    
env:
  BROWSER_PARAMS: "--window-size=1920,1080 --allowed-ips --no-sandbox"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        working-directory: ./Behavioral.Automation.Selenium/Behavioral.Automation.DemoScenarios
        run: dotnet build -c Release --no-restore
      - name: Test
        working-directory: ./Behavioral.Automation.Selenium/Behavioral.Automation.DemoScenarios
        run: dotnet test -c Release --no-build --verbosity normal
